version: "3"
services: 
 myweb: 
  build: ./myweb
  ports: 
   - 3000:3000
  links:  
   - mysql1
 mysql1: 
  build: ./mydb
  environment: 
   MYSQL_ROOT_PASSWORD: 123456
  ports:  
   - 3306:3306
  
