from nginx
add node-v8.9.1-linux-x64.tar.xz /usr/local
run ln -s  /usr/local/node-v8.9.1-linux-x64/bin/node /usr/local/bin/node && ln -s  /usr/local/node-v8.9.1-linux-x64/bin/npm /usr/local/bin/npm
expose 80
